//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMenu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MenuDBEntities : DbContext
    {
        public MenuDBEntities()
            : base("name=MenuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwItems> vwItems { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<OrderInfoItem> OrderInfoItem { get; set; }
    
        public virtual ObjectResult<GetIngrediens_Result> GetIngrediens(Nullable<int> item_ID)
        {
            var item_IDParameter = item_ID.HasValue ?
                new ObjectParameter("Item_ID", item_ID) :
                new ObjectParameter("Item_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIngrediens_Result>("GetIngrediens", item_IDParameter);
        }
    
        public virtual ObjectResult<GetOrdersByPhone_Result> GetOrdersByPhone(string phone)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersByPhone_Result>("GetOrdersByPhone", phoneParameter);
        }
    
        public virtual ObjectResult<string> GetOrdersStatus(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetOrdersStatus", orderIDParameter);
        }
    
        public virtual ObjectResult<GetUnDoneOrders_Result> GetUnDoneOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnDoneOrders_Result>("GetUnDoneOrders");
        }
    }
}
