//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfoItem
    {
        public int ID_OrderInfo { get; set; }
        public int ID_Item { get; set; }
        public int ID_Primary { get; set; }
    }
}
